# Generated by Django 3.1.1 on 2020-09-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_remove_answer_onwhatquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dateAnswer',
            field=models.TextField(default='', verbose_name='Время'),
        ),
    ]
