# Generated by Django 3.1.1 on 2020-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_answer_dateanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(verbose_name='глобальный счетчик')),
            ],
            options={
                'verbose_name': 'Счетчик',
            },
        ),
    ]
