# Generated by Django 3.1.1 on 2020-09-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_globalnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnum',
            name='gnum',
            field=models.PositiveIntegerField(default=1, verbose_name='#'),
        ),
    ]
