# Generated by Django 3.1.1 on 2020-09-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_globalnum_gnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typeOfProfile',
            field=models.TextField(default='Не определился', verbose_name='Состояние профиля'),
        ),
    ]
